// IF

// SE A DADE É MAIOR OU IGUAL QUE 18, A PESSOA É ADULTA
// MAIOR: >      |       MAIOR OU IGUAL: >=
// SE É MENOR QUE 18, NÃO É ADULTA

// SE IDADE É MAIR OU IGUAL À 18

// SE IDADE É MENOR QUE 18

// SE COME AÇUCAR, CUIDADO PARA NÃO ENGORDAR
// IGUAL: ===

// SE comeAcucar É IGUAL À sim

// SE comeAcucar É IGUAL À nao
