// FUNCAO

// CRIAR UMA FUNÇÃO DE NOME comprimetar

// CHAMAR A FUNÇÃO 2 veses -> NOME DA FUNÇÃO SEGUIDO DE () (ABRE E FECHA PARENTESIS)

// CRIAR FUNCAO MOSTRAR DOBRO, PASSANDO UM NUMERO COMO PARAMETRO

// CHAMAR mostrarDobro 2 x

// SOMAR 2 NÚMEROS
// 2 PARÂMETROS SEPARADOS POR VÍRGULA
